kind: Service
apiVersion: v1
metadata:
  name: trainscheduleservice
spec:
  type: NodePort
  selector:
    app: trainschedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainscheduledeployment
  labels:
    app: trainschedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trainschedule
      track: stable
  template:
    metadata:
      labels:
        app: trainschedule
        track: stable
    spec:
      containers:
      - name: trainschedule
        image: dk2022/webapp:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
